#!/usr/bin/with-contenv bash
	screen -D -m -S \
	rtorrent s6-setuidgid abc /usr/bin/rtorrent -n -o import=/rtorrent.rc

until [ -e "/config/rtorrent_sess/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(< /config/rtorrent.lock cut -d '+' -f 2)
tail -n 1 -f /config/log/rtorrent.log --pid "$rtorrent_pid"
