#!/usr/bin/with-contenv bash

mkdir -p /config/rtorrent_sess
# delete lock file if exists
[[ -e /config/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent_sess/rtorrent.lock

# permissions
chown abc:abc \
	/downloads

chown -R abc:abc \
	/config \
	/run
